version: '3.8'

services:
  auth_service:
    build: ./auth_service
    ports:
      - "4000:4000"
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb

  tasks_service:
    build: ./tasks_service
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb

  api_gateway:
    build: ./api_gateway
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - TASKS_SERVICE_URL=${TASKS_SERVICE_URL}
    depends_on:
      - auth_service
      - tasks_service

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
